complete array
stasya-k/study pull request #1
Opened 2020-08-23 10:50 UTC by stasya-k

2021-11-10 04:55 UTC, Yoffic requested changes

2021-11-10 04:55 UTC, Yoffic commented on test/exercise/arrays/solution.rb
> +        end
Можно также использовать однострочную конструкцию { |x| x ? 0 : 1 }, как это сделано ниже для map

2021-11-10 04:55 UTC, Yoffic commented on test/exercise/arrays/solution.rb
> +        while low <= high
Двоичный поиск нужно реализовать, используя рекурсию.

2021-11-13 11:06 UTC, stasya-k commented on test/exercise/arrays/solution.rb
> +        end
точно, исправила!

2021-11-13 11:07 UTC, stasya-k commented on test/exercise/arrays/solution.rb
> +        while low <= high
Пропустила почему-то это в задании. Переписала.

2021-11-15 01:54 UTC, Yoffic commented on test/exercise/arrays/solution.rb
> +
Кажется здесь закралась лишняя пустая строка

2021-11-15 01:54 UTC, Yoffic approved these changes

2021-11-15 13:16 UTC, merged